name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Ensure app directory exists
            mkdir -p ~/app
            cd ~/app

            # Pull latest code from GitHub
            if [ -d .git ]; then
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }} .
            fi

            # Sync files to Nginx web root
            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html/

            # Fix permissions
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            # Restart Nginx service
            sudo systemctl restart nginx
          EOF
