name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 and update Nginx
        run: |
          ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Make sure web root exists
            sudo mkdir -p /var/www/html

            # Remove old files
            sudo rm -rf /var/www/html/*

            # Copy new files from repo
            sudo cp -r ~/app/* /var/www/html/

            # Set correct permissions
            sudo chmod -R 755 /var/www/html
            sudo chown -R www-data:www-data /var/www/html

            # Restart Nginx
            sudo systemctl restart nginx
          EOF
